name: INSEAD Newsroom Scraper

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs at minute 0 every 12th hour (e.g., 00:00, 12:00 UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudscraper beautifulsoup4 pyairtable

      - name: Run scraper script
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          python inseadnews.py

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: insead-scraper-log
          path: insead_newsroom_scrape.log
